# 测试飞书告警
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: feishu-test-alert
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
    - name: feishu-test
      rules:
        - alert: FeishuTestAlert
          expr: vector(1)
          for: 0s
          labels:
            severity: warning
            service: test-service
          annotations:
            description: "这是一条通过 PrometheusAlert 发送的飞书测试告警"
            summary: "PrometheusAlert 飞书告警测试"