---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cascade-pod-kill-adservice
  namespace: monitoring
  labels:
    chaos.mes.org/type: cascade-failure
    chaos.mes.org/part: "part1"
spec:
  action: pod-kill
  mode: one
  value: "1"
  duration: "2m"
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: adservice
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cascade-pod-kill-currency
  namespace: monitoring
  labels:
    chaos.mes.org/type: cascade-failure
    chaos.mes.org/part: "part2"
spec:
  action: pod-kill
  mode: one
  value: "1"
  duration: "2m"
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: currencyservice
